---
# Install Islandora Karaf Compontents

- name: Wait for Apache to Start
  wait_for: host={{ drupal_webserver_host }} port={{ drupal_webserver_port }}
  
- name: Wait for Tomcat to Start
  wait_for: host={{ tomcat_host }} port={{ tomcat_port }}
  
- name: Wait for JMS to Start
  wait_for: host={{ tomcat_host }} port={{ jms_port }}

- name: Wait for Karaf to be ready.
  shell: "service karaf-service status"
  register: result
  until: result.rc == 0
  retries: 10
  delay: 5
  changed_when: false

- name: Deploy Components
  template: >-
    src={{ item }} dest={{ download_directory }}/{{ item }}
  with_items:
    - islandora_sync_gateway.script
    - islandora_indexing_triplestore.script
    - watch.script

- name: "Install Islandora Karaf Components"
  shell: >
    {{ karaf_client }} -f {{ download_directory }}/{{ item.script }} && sleep 10
    creates={{ karaf_home }}/etc/{{ item.creates }}
  environment:
    JAVA_HOME: "{{ java_home }}" 
  with_items:
    - script: islandora_sync_gateway.script
      creates: ca.islandora.camel.sync.cfg
    - script: islandora_indexing_triplestore.script
      creates: ca.islandora.camel.indexing.triplestore.cfg

  # We have to overide the default settings with the appropriate passwords etc.
- name: Deploy Karaf Configuration
  template: >
    src={{ item }} dest={{ karaf_home }}/etc
  with_items:
    - ca.islandora.camel.sync.cfg
    - ca.islandora.sync.cfg
    - org.fcrepo.camel.indexing.triplestore.cfg
    - ca.islandora.camel.indexing.triplestore.cfg

- name: Watch Maven Repository 
  shell: >
    {{ karaf_client }} -f {{ download_directory }}/watch.script && sleep 10
  environment:
    JAVA_HOME: "{{ java_home }}" 
