#!/bin/bash

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

random_password() {
  LC_ALL=C
  tr -dc _A-Za-z0-9 < /dev/urandom | head -c${1:-32}; echo;
}

generate_secrets() {
    cat <<EOF > $DIR/../secrets.yml
---
mysql_root_password: $(random_password)
tomcat_admin_password: $(random_password)
drupal_site_account_password: $(random_password)
drupal_site_db_password: $(random_password)
EOF
}

main () {
    if ! [ -f $DIR/../secrets.yml ]; then
        generate_secrets
    fi
}
main
